fastlane_version "2.68.2"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload RxDialog"
  lane :release_dialog_rx do
    gradle(task: "clean")
    gradle(task: ":dialog-rx:install")
    gradle(task: ":dialog-rx:bintrayUpload")
  end

  desc "Deploy all libs to maven"
  lane :deploy do
    release_dialog_rx
  end
end
